//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaEsportYesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsemkaEsportEntities : DbContext
    {
        public EsemkaEsportEntities()
            : base("name=EsemkaEsportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<schedule_detail> schedule_detail { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<team_detail> team_detail { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
