//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaEsportYesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_detail
    {
        public int id { get; set; }
        public int schedule_id { get; set; }
        public int user_id { get; set; }
        public int total_ticket { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual schedule schedule { get; set; }
        public virtual user user { get; set; }
    }
}
