//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaEsportYesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_detail
    {
        public int id { get; set; }
        public int team_id { get; set; }
        public int player_id { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual player player { get; set; }
        public virtual team team { get; set; }
    }
}
